/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingGeneralRouteImport } from './routes/setting/general'
import { Route as ChatIdRouteImport } from './routes/chat/$id'

const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingGeneralRoute = SettingGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setting': typeof SettingRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/setting/general': typeof SettingGeneralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setting': typeof SettingRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/setting/general': typeof SettingGeneralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/setting': typeof SettingRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/setting/general': typeof SettingGeneralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/setting' | '/chat/$id' | '/setting/general'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/setting' | '/chat/$id' | '/setting/general'
  id: '__root__' | '/' | '/setting' | '/chat/$id' | '/setting/general'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingRoute: typeof SettingRouteWithChildren
  ChatIdRoute: typeof ChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting/general': {
      id: '/setting/general'
      path: '/general'
      fullPath: '/setting/general'
      preLoaderRoute: typeof SettingGeneralRouteImport
      parentRoute: typeof SettingRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingRouteChildren {
  SettingGeneralRoute: typeof SettingGeneralRoute
}

const SettingRouteChildren: SettingRouteChildren = {
  SettingGeneralRoute: SettingGeneralRoute,
}

const SettingRouteWithChildren =
  SettingRoute._addFileChildren(SettingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingRoute: SettingRouteWithChildren,
  ChatIdRoute: ChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
